language: python
python:
  - "3.4"
install:
  - pip install requests
  - pip install coveralls
  - pip install python-coveralls
  - pip install coverage       # Add me to install coverage.py
  - pip install nose           # Add me to install nose
script: nosetests --with-coverage --with-doctest
after_success:
  - coveralls
after_failure:
  - coveralls